name: Factorio E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create mod directory
        run: |
          mkdir -p ~/factorio/mods/factorio-tycoon-2
          cp -r . ~/factorio/mods/factorio-tycoon-2/

      - name: Download Factorio headless
        run: |
          wget -q https://factorio.com/get-download/stable/headless/linux64 -O factorio.tar.xz
          tar -xJf factorio.tar.xz

      - name: Configure Factorio server
        run: |
          echo '{"mods":[{"name":"factorio-tycoon-2","enabled":true}]}' > ./factorio/mods/mod-list.json

      - name: Create new save and run server
        id: run_server
        run: |
          set +e
          ./factorio/bin/x64/factorio --create ./factorio/saves/tycoon-test.zip
          SERVER_OUTPUT=$(./factorio/bin/x64/factorio --start-server ./factorio/saves/tycoon-test.zip --server-settings ./factorio/data/server-settings.example.json 2>&1)
          echo "$SERVER_OUTPUT" > server_output.log
          if echo "$SERVER_OUTPUT" | grep -i "error"; then
            echo "::error ::Factorio server encountered errors"
            echo "$SERVER_OUTPUT"
            exit 1
          else
            echo "Factorio server started successfully"
          fi

      - name: Upload server logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: server-logs
          path: server_output.log
